# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0002_auto_20170819_2255'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(unique=True, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='views')),
                ('likes', models.PositiveIntegerField(default=0, editable=False, verbose_name='likes')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('tags', models.ManyToManyField(blank=True, to='index.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'ordering': ['-created_time'],
            },
        ),
    ]
