# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20170829_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(max_length=6000, verbose_name='address'),
        ),
    ]
