# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('written', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_time'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
