# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('written', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='excerpt'),
        ),
    ]
