# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('written', '0002_auto_20170821_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified time'),
        ),
    ]
