# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('written', '0003_auto_20170916_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='a_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
