# Generated by Django 5.2.17 on 2026-09-29 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20170925_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=300, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
